version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure Dockerfile exists for Django
    container_name: django-app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - ollama
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: pixeladvant_hiring
      DATABASE_USER: root
      DATABASE_PASSWORD: PixelAdvant@123
    volumes:
      - /app
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: PixelAdvant@123
      MYSQL_DATABASE: pixeladvant_hiring
      MYSQL_USER: myuser
      MYSQL_PASSWORD: PixelAdvant@123
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  ollama:
    build:
      context: .
      dockerfile: Dockerfile_ollama  # Ensure Dockerfile_ollama exists for Ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge