# Generated by Django 5.2.1 on 2025-05-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('CandidateID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Resume', models.FileField(upload_to='resumes/')),
                ('ProfileCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'candidates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255)),
                ('RoleID', models.IntegerField()),
                ('Email', models.CharField(blank=True, max_length=255)),
                ('PasswordHash', models.CharField(blank=True, max_length=255)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_details',
                'managed': False,
            },
        ),
    ]
