# Generated by Django 5.2.1 on 2025-05-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserroleDetails',
            fields=[
                ('RoleID', models.IntegerField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'userrole',
                'managed': False,
            },
        ),
    ]
