# Generated by Django 5.2.1 on 2025-05-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userroledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('RequisitionID', models.AutoField(primary_key=True, serialize=False)),
                ('PositionTitle', models.CharField(max_length=191)),
                ('HiringManagerID', models.IntegerField()),
                ('Status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Posted', 'Posted')], default='Draft', max_length=50)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
