# Generated by Django 5.2.1 on 2025-06-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jobrequisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('PostingID', models.AutoField(primary_key=True, serialize=False)),
                ('RequisitionID', models.IntegerField(db_index=True)),
                ('PostingType', models.CharField(choices=[('Intranet', 'Intranet'), ('External', 'External'), ('Private', 'Private')], max_length=10)),
                ('PostingStatus', models.CharField(choices=[('Pending', 'Pending'), ('Posted', 'Posted'), ('Closed', 'Closed')], default='Pending', max_length=10)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobposting',
            },
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='No_of_positions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='recruiter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelTable(
            name='jobrequisition',
            table='jobrequisition',
        ),
        migrations.CreateModel(
            name='JobRequisitionExtraDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LegalEntity', models.CharField(max_length=255)),
                ('PrimaryLocation', models.CharField(max_length=255)),
                ('GeoZone', models.CharField(blank=True, max_length=255, null=True)),
                ('EmployeeGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('EmployeeSubGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('BusinessLine', models.CharField(blank=True, max_length=255, null=True)),
                ('BusinessUnit', models.CharField(blank=True, max_length=255, null=True)),
                ('Division', models.CharField(blank=True, max_length=255, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('RequisitionType', models.CharField(max_length=255)),
                ('CareerLevel', models.CharField(max_length=255)),
                ('IsContract', models.BooleanField(default=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('Band', models.CharField(blank=True, max_length=255, null=True)),
                ('SubBand', models.CharField(blank=True, max_length=255, null=True)),
                ('ClientInterview', models.BooleanField(default=False)),
                ('SecondarySkill', models.CharField(blank=True, max_length=255, null=True)),
                ('ModeOfWorking', models.CharField(max_length=255)),
                ('Skills', models.TextField()),
                ('RequisitionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobrequisition')),
            ],
            options={
                'db_table': 'jobrequisitionextradetails',
            },
        ),
    ]
