# Generated by Django 5.2.1 on 2025-06-06 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jobrequisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('PostingID', models.AutoField(primary_key=True, serialize=False)),
                ('RequisitionID', models.IntegerField(db_index=True)),
                ('PostingType', models.CharField(choices=[('Intranet', 'Intranet'), ('External', 'External'), ('Private', 'Private')], max_length=10)),
                ('PostingStatus', models.CharField(choices=[('Pending', 'Pending'), ('Posted', 'Posted'), ('Closed', 'Closed')], default='Pending', max_length=10)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobposting',
            },
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='No_of_positions',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='Recruiter',
            field=models.CharField(blank=True, default='Not Assigned', max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='HiringManagerID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='PositionTitle',
            field=models.CharField(blank=True, default='Not Provided', max_length=191, null=True),
        ),
        migrations.AlterModelTable(
            name='jobrequisition',
            table='jobrequisition',
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(blank=True, default='Non-Billable', max_length=50, null=True)),
                ('billing_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_details', to='myapp.jobrequisition')),
            ],
            options={
                'db_table': 'billing_details',
            },
        ),
        migrations.CreateModel(
            name='InterviewTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, default='Unknown ID', max_length=50, null=True)),
                ('name', models.CharField(blank=True, default='Unknown Interviewer', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_team', to='myapp.jobrequisition')),
            ],
            options={
                'db_table': 'interview_team',
            },
        ),
        migrations.CreateModel(
            name='JobRequisitionExtraDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LegalEntity', models.CharField(max_length=255)),
                ('PrimaryLocation', models.CharField(max_length=255)),
                ('Geo_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('EmployeeGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('EmployeeSubGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('BusinessLine', models.CharField(blank=True, max_length=255, null=True)),
                ('BusinessUnit', models.CharField(blank=True, max_length=255, null=True)),
                ('Division', models.CharField(blank=True, max_length=255, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('RequisitionType', models.CharField(max_length=255)),
                ('CareerLevel', models.CharField(max_length=255)),
                ('Is_contract', models.BooleanField(default=False)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField(blank=True, null=True)),
                ('Band', models.CharField(blank=True, max_length=255, null=True)),
                ('SubBand', models.CharField(blank=True, max_length=255, null=True)),
                ('Client_interview', models.BooleanField(default=False)),
                ('Secondary_skill', models.CharField(blank=True, max_length=255, null=True)),
                ('ModeOfWorking', models.CharField(max_length=255)),
                ('Skills', models.TextField()),
                ('RequisitionID', models.ForeignKey(db_column='RequisitionID', on_delete=django.db.models.deletion.CASCADE, to='myapp.jobrequisition')),
            ],
            options={
                'db_table': 'jobrequisitionextradetails',
            },
        ),
        migrations.CreateModel(
            name='PostingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(blank=True, default='0+ years', max_length=255, null=True)),
                ('designation', models.CharField(blank=True, default='Unknown Role', max_length=255, null=True)),
                ('job_category', models.CharField(blank=True, default='General', max_length=255, null=True)),
                ('job_region', models.CharField(blank=True, default='Global', max_length=255, null=True)),
                ('internal_job_description', models.TextField(blank=True, default='No Description', null=True)),
                ('external_job_description', models.TextField(blank=True, default='No Description Available', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posting_details', to='myapp.jobrequisition')),
            ],
            options={
                'db_table': 'posting_details',
            },
        ),
        migrations.CreateModel(
            name='RequisitionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_title', models.CharField(blank=True, default='Unknown Title', max_length=255, null=True)),
                ('external_title', models.CharField(blank=True, default='Unknown Title', max_length=255, null=True)),
                ('role_position', models.CharField(blank=True, default='Not Provided', max_length=255, null=True)),
                ('business_line', models.CharField(blank=True, default='General Business', max_length=255, null=True)),
                ('business_unit', models.CharField(blank=True, default='General Unit', max_length=255, null=True)),
                ('division_name', models.CharField(blank=True, default='Unknown Division', max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, default='Unknown Department', max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, default='Not Provided', max_length=255, null=True)),
                ('geo_zone', models.CharField(blank=True, default='Global', max_length=255, null=True)),
                ('employee_group', models.CharField(blank=True, default='General Employee Group', max_length=255, null=True)),
                ('employee_sub_group', models.CharField(blank=True, default='General Sub Group', max_length=255, null=True)),
                ('contract_start', models.DateField(blank=True, default=None, null=True)),
                ('contract_end', models.DateField(blank=True, default=None, null=True)),
                ('career_level', models.CharField(blank=True, default='Entry Level', max_length=50, null=True)),
                ('band_level', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('sub_band_level', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('primary_skills', models.TextField(blank=True, default='Not Specified', null=True)),
                ('secondary_skills', models.TextField(blank=True, default='None', null=True)),
                ('work_mode', models.CharField(blank=True, default='Office', max_length=50, null=True)),
                ('requisition_type', models.CharField(blank=True, default='Standard Hiring', max_length=50, null=True)),
                ('client_interview', models.BooleanField(default=False)),
                ('required_score', models.IntegerField(blank=True, default=0, null=True)),
                ('coordinator_name', models.CharField(blank=True, default='Not Assigned', max_length=255, null=True)),
                ('coordinator_team', models.TextField(blank=True, default='No Team Assigned', null=True)),
                ('isg_team_name', models.TextField(blank=True, default='No ISG Team Assigned', null=True)),
                ('interviewer_employee_id', models.CharField(blank=True, default='Not Available', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.jobrequisition')),
            ],
            options={
                'db_table': 'requisition_details',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_type', models.CharField(blank=True, default='General Team', max_length=50, null=True)),
                ('team_name', models.CharField(blank=True, default='Unknown Team', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='myapp.jobrequisition')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
